[package]
name = "schmeta"
version = "0.1.0"
edition = "2021"

[dependencies]
calamine = "0.26.1"
clap = { version = "4.5.26", features = ["derive"] }
colored = "3.0.0"
serde = { version = "1.0.217", features = ["derive"] }